config/routes.rb
Rails.application.routes.draw do\
  devise_for :users

  resources :friendships,   only: [:create, :update, :destroy]
  resources :users,         only: [:index, :show, :edit, :update]

  resources :posts,         only: [:create] do
    resources :comments,    only: [:create]
  end
  resources :likes,         only: [:create, :destroy]

  root 'static_pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id } 
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader

  validates :user_id, presence: true
  validates :content, presence: true

  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end

  def picture_posted
    :picture.present?
  end


end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100" },
  default_url: "missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/


  has_many :friendships
  has_many :inverse_friendships, class_name: "Friendship", :foreign_key => "friend_id"

  has_many :friends, -> { where(friendships: { accepted: true }) }, :through => :friendships
  has_many :inverse_friends, -> { where(friendships: { accepted: true }) }, :through => :inverse_friendships, :source => :user

  has_many :pending_requests, -> { where(friendships: { accepted: false }) }, :through => :friendships, source: :friend
  has_many :sent_requests, -> { where(friendships: { accepted: false }) }, :through => :inverse_friendships, :source => :user

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  def feed
    Post.where("user_id in (?) OR user_id in (?) OR user_id = ?", friend_ids, inverse_friend_ids, id)
  end

  def friend?
    User.where("id in (?) OR id in (?) OR id in (?) OR id in (?) OR id = ?", friend_ids, inverse_friend_ids, pending_request_ids, sent_request_ids, id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # redirects to users_show_url on login
  def after_sign_in_path_for(resource_or_scope)
   current_user
  end

  # redirects to root_url on logout
  def after_sign_out_path_for(resource_or_scope)
    root_url
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = current_user.comments.build(comment_params)
    if @comment.save
      flash[:notice] = "Created comment"
      redirect_to current_user
    else
      flash[:notice] = "Failed to create comment"
      redirect_to current_user
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:content, :post_id)
    end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def create
    @friendship = current_user.friendships.build(:friend_id => params[:friend_id])
    if @friendship.save
      flash[:notice] = "Friend requested."
      redirect_to current_user
    else
      flash[:notice] = "Unable to like friend."
      render :action => "new"
    end
  end

  def update
    @friendship = Friendship.find_by("user_id = ? OR friend_id = ?", params[:id], params[:id])
    @friendship.accepted = true
    @friendship.save
    if @friendship.save
      redirect_to current_user
      flash[:notice] = "Friend added."
    else
      redirect_to current_user
      flash[:error] = "Unable to accept friendship"
    end
  end

  def destroy
    @friendship = Friendship.find_by("user_id = ? OR friend_id = ?", params[:id], params[:id])
    @friendship.destroy
    flash[:notice] = "Removed friendship."
    redirect_to current_user
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @likes = current_user.likes.build(:post_id => params[:post_id])
    if @likes.save
      flash[:notice] = "Liked post"
      redirect_to current_user
    else
      flash[:notice] = "Can't like post.. sorry about that."
      redirect_to current_user
    end
  end

  def destroy
    @like = Like.find_by(post_id: params[:user_id])
    @like.destroy if @like != nil
    flash[:notice] = "Unliked post"
    redirect_to current_user
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:notice] = "Post created!"
      redirect_to current_user
    else
      flash[:notice] = "Post failed! Please add some text."
      redirect_to current_user
    end
  end

  private

    def post_params
      params.require(:post).permit(:content, :picture)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @users = User.all
    @user = User.find(params[:id])

    @posts = @user.posts
    @post = @user.posts.build

    @likes = @user.likes
    @like = @user.likes.build

    @comments = @user.comments
    @comment = @user.comments.build

    @feed_items = @user.feed

  end

  def index
    @users = User.all
    @friend_request = current_user.friend?
    @user = current_user
  end

  def new
  end

  def create
    @user = User.create(user_params)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to current_user
    else
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :location, :occupation, :avatar)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def avatar_url(user)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=48"
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Wasteland
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{:href => "https://fonts.googleapis.com/css?family=Roboto:300,400,700", :rel => "stylesheet"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Merriweather:300", :rel => "stylesheet"}/

    %link{:href =>'http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css', :rel => 'stylesheet'}

  %body
    %header
      .container
        .brand
          = link_to 'Wasteland', root_path
        - if user_signed_in?
          .nav-left
            = link_to "Home", user_path(current_user)
            = link_to "Users", users_path
        .nav-right
          - if user_signed_in?
            = link_to "Log out", destroy_user_session_path, :method => :delete
          - else
            = link_to "Sign up", new_user_registration_path
            = link_to "Log in", new_user_session_path
  .container
    .flex
      - if user_signed_in?
        %aside
          %section
            - if user_signed_in?
              .avatar-image= image_tag @user.avatar.url(:thumb)
              %p
                %i.ion-email
                = current_user.email
              %p
                %i.ion-person
                = current_user.name
              %p
                %i.ion-location
                = current_user.location
              %p
                %i.ion-android-walk
                = current_user.occupation
              %p= link_to 'Edit', edit_user_path(current_user)


          - if user_signed_in?
            %section
              %h4 Friends
              - current_user.friends.each do |friend|
                %p
                  = friend.email
                  = link_to friendship_path(id: friend.id), :method => :delete do
                    %span.float-right.ion-trash-a
              - current_user.inverse_friends.each do |friend|
                %p
                  = friend.email
                  = link_to friendship_path(id: friend.id), :method => :delete do
                    %span.float-right.ion-trash-a

              %br
              %h4 Sent Requests
              - current_user.pending_requests.each do |request|
                %p= request.email

              %br
              %h4 Pending Requests
              - current_user.sent_requests.each do |request|
                %p
                  = request.email
                  = link_to "Accept", friendship_path(id: request.id), method: "put"
                  = link_to "Decline", friendship_path(id: request.id), method: :delete

      %main
        - flash.each do
          .notice= notice
        = yield

app/views/layouts/static_pages.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Wasteland
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{:href => "https://fonts.googleapis.com/css?family=Roboto:300,400,700", :rel => "stylesheet"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Merriweather:300", :rel => "stylesheet"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Nothing+You+Could+Do", :rel => 'stylesheet'}


    %link{:href =>'http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css', :rel => 'stylesheet'}

  %body.home
    = yield

app/views/static_pages/home.haml
.welcome
  .home-brand W
  %h1 Wasteland
  %p The non-social network
  = link_to "Sign up", new_user_registration_path, class: 'button button-primary'
  = link_to "Log in", new_user_session_path, class: 'button button-primary'

app/views/users/edit.haml
%section
  %h2 Edit
  = form_for(@user) do |f|
    = f.label         :name
    = f.text_field    :name
    = f.label         :location
    = f.text_field    :location
    = f.label         :occupation
    = f.text_field    :occupation
    %p= f.label       :avatar
    = f.file_field    :avatar
    %br
    %br
    = f.submit 'Save', class: 'button button-primary'

app/views/users/index.haml
%section
  %h2 Add Users
  - @users.each do |user|
    - unless user.friend?.exists? current_user
      %p
        = user.email
        = link_to "Add friend", friendships_path(:friend_id => user), :method => :post
    - else
      %p
        = user.email

app/views/users/show.haml
%section.post-new
  = form_for @post do |f|
    .form
      = f.text_area :content, placeholder: "Create new post", rows: '1'
      = f.submit 'Post', class: 'button button-primary'
    .file-upload
      = f.file_field :picture

.post-feed
  - @feed_items.each do |post|
    .post
      %b= post.user.email
      %p= post.content
      %p= image_tag post.picture.url if post.picture?

    .post-details
      %ul
        %li
          = post.likes.count
          likes
        %li
          = link_to likes_path(:post_id => post), :method => :post do
            .ion-thumbsup
        %li
          = link_to like_path(:user_id => post), :method => :delete do
            .ion-thumbsdown
      %small
        posted
        = time_ago_in_words(post.created_at)
        ago

    - post.comments.each do |comment|
      .post-comment
        %small
          %b= comment.user.email
          replying to
          = post.user.email
        %p= comment.content

    .post-reply
      = form_for(:comment, url: post_comments_path(post_id: post.id), :method => "post") do |f|
        = f.text_area :content, placeholder: "Post comment", rows: '1'
        = f.hidden_field :post_id, :value => post.id
        = f.submit 'Post', class: 'button button-primary'

:javascript
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });